### ISSUE TITLE
条件分支网关

### ISSUE THREAD

**Issue by dengjun** [xhongc/dj-flow#4]
界面上加入条件分支网关后，不能保存，条件分支网关的inputs   node_data["inputs"]    这个key不存在

Traceback (most recent call last):
  File "D:\GitHub\streamflow\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\streamflow\venv\lib\site-packages\rest_framework\mixins.py", line 70, in update
    self.perform_update(serializer)
  File "D:\GitHub\streamflow\venv\lib\site-packages\rest_framework\mixins.py", line 80, in perform_update
    serializer.save()
  File "D:\GitHub\streamflow\applications\flow\serializers.py", line 82, in save
    self.update(instance=self.instance, validated_data=self.validated_data)
  File "D:\GitHub\streamflow\applications\flow\serializers.py", line 212, in update
    raise serializers.ValidationError(f"流程编排错误，请检查!：{e}")
rest_framework.exceptions.ValidationError: [ErrorDetail(string="流程编排错误，请检查!：'inputs'", code='invalid')]
During handling of the above exception, another exception occurred:

**Comment by xhongc** [comment]
有段时间没打理这个项目了，竟然还有在使用的人

**Comment by xhongc** [comment]
用来学习的话，可以自行查看代码
